"""Generate docs/ASSETS.md from assets/manifest.json so the catalog cannot drift from the build."""
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
BLENDER="& 'C:\\Program Files\\Blender Foundation\\Blender 5.1\\blender.exe' --background --disable-autoexec --python-exit-code 1 --python"


def generate(manifest):
    assets=manifest['assets']
    uploaded=[n for n,a in assets.items() if a.get('assetId')]
    lines=[
        '# Ghostlight Hollow assets',
        '',
        'Generated by `tools/gen_assets_doc.py` from `assets/manifest.json`. Do not hand-edit the table.',
        f'{len(assets)} assets, {len(uploaded)} uploaded. Runtime loads an asset only when its ID is non-zero;',
        'otherwise `World.build()` keeps the primitive version of that piece.',
        '',
        '| Asset | Zone | Triangles | Meshes | Footprint X,Y,Z (studs) | Roles | Status | Preview |',
        '| --- | --- | ---: | ---: | --- | --- | --- | --- |',
    ]
    for name in sorted(assets,key=lambda n:(assets[n].get('zone',''),n)):
        a=assets[name]
        fp=', '.join(f'{v:.1f}' for v in a['footprint'])
        status=f"uploaded {a['assetId']}" if a.get('assetId') else 'not uploaded'
        lines.append(f"| {name} | {a.get('zone','Props')} | {a['triangles']} / {a['triangleBudget']} | {a.get('meshCount','')} | {fp} "
                     f"| {', '.join(a['roles'])} | {status} | [front](../assets/previews/{name}_front.png) [top](../assets/previews/{name}_top.png) |")
    lines+=[
        '',
        '## Rebuild, preview, upload, harvest (PowerShell, project directory)',
        '',
        'Close Blender before rebuilding `town.blend`. Never rebuild it between an upload and the ID harvest.',
        '',
        '```powershell',
        f'{BLENDER} tools/blender/build_assets.py -- --out assets',
        f'{BLENDER} tools/blender/render_previews.py -- --out assets',
        '```',
        '',
        'Upload: open `assets/town.blend`, press N over the 3D viewport, open the Roblox tab, log in if asked, choose',
        'your account under Upload to, select the collections named in the table (folder icons in the Outliner, not',
        'the meshes), click Upload, wait for a green checkmark on each, press Ctrl+S, close Blender. Collections that',
        'already carry a `Roblox Package ID` upload as a new version of the same asset.',
        '',
        '```powershell',
        f'{BLENDER} tools/blender/harvest_ids.py',
        'python tools/gen_asset_ids.py',
        'python tools/gen_assets_doc.py',
        'python tools/build_place.py',
        'python tools/build_place.py --test',
        'python tools/verify.py',
        '```',
        '',
        '## Runtime notes',
        '',
        '- Visible meshes are non-collidable; every asset ships a `Collision` mesh that is invisible and collidable.',
        '- MeshParts are coloured by the role suffix of their name. `Glow` and `Accent` are Neon; `Accent` takes a',
        '  per-instance colour (Haunt hues, blue-white fountain spirit, violet portal and altar).',
        '- Whole-town budgets: 400,000 triangles, 500 MeshParts, 1,500 primitives, 60 lights, 3 shadowed lights.',
        '- A configured asset that fails to load produces a labelled placeholder and one warning per asset.',
        '',
    ]
    return '\n'.join(lines)


if __name__=='__main__':
    manifest=json.loads((ROOT/'assets/manifest.json').read_text(encoding='utf-8'))
    output=ROOT/'docs/ASSETS.md'
    output.write_text(generate(manifest),encoding='utf-8')
    print(f'Generated {output.relative_to(ROOT)} ({len(manifest["assets"])} assets)')
