"""Generate Roblox metadata from the asset manifest; zero means not yet uploaded."""
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]


def generate(manifest):
    lines=['-- Generated by tools/gen_asset_ids.py. Do not hand-edit.','return {']
    for name,asset in sorted(manifest['assets'].items()):
        if not name.isidentifier(): raise ValueError(f'Invalid asset name: {name}')
        identifier=asset.get('assetId',0)
        if type(identifier) is not int or identifier<0 or identifier>2**53-1:
            raise ValueError(f'{name}: invalid asset ID')
        size=asset['footprint']
        if len(size)!=3 or any(type(n) not in (int,float) or not 0<n<10000 for n in size):
            raise ValueError(f'{name}: invalid footprint')
        roles=asset['roles']
        allowed={'Stone','Wood','Roof','Metal','Glass','Glow','Accent','Foliage','Ground','Water','Collision'}
        if not roles or any(r not in allowed for r in roles): raise ValueError(f'{name}: invalid roles')
        roles_text=', '.join(json.dumps(r) for r in roles)
        dimensions=', '.join(str(v) for v in size)
        lines.append(f'    {name}={{Id={identifier}, Footprint=Vector3.new({dimensions}), Roles={{{roles_text}}}}},')
    return '\n'.join(lines+['}',''])


if __name__=='__main__':
    manifest=json.loads((ROOT/'assets/manifest.json').read_text())
    output=ROOT/'src/shared/AssetIds.luau'
    output.write_text(generate(manifest),encoding='utf-8')
    print(f'Generated {output.relative_to(ROOT)} ({len(manifest["assets"])} assets)')
